// react-with-graphql/src/pages/Login.js
import React, { useState } from 'react';
import { Form, Icon, Input, Button, Row, Col, Layout, Modal } from 'antd';
import { useQuery, useMutation } from '@apollo/react-hooks';
import { useHistory } from 'react-router-dom';
import { GET_LOCAL_STATE } from '@/graphql/queries/localState';
import { LOGIN } from '@/graphql/mutations/localState';

import SignUp from '@/components/example/user/SignUp';

const { Content } = Layout;

function Login(props) {
  const { loading, error, data } = useQuery(GET_LOCAL_STATE);
  const [login] = useMutation(LOGIN);
  const history = useHistory();
  const [modalState, setModalState] = useState({
    visible: false,
  });

  if (loading) return <p>Loading...</p>;
  if (error) return <p>Error!</p>;

  const { getFieldDecorator } = props.form;
  const { users } = data;

  const getUser = ({ email }) =>
    Object.values(users).find(obj => obj.email === email);

  const isValidAccount = ({ email, password }) => {
    const user = getUser({ email });
    return user && user.password === password;
  };

  const onLogin = e => {
    e.preventDefault();
    props.form.validateFields((err, values) => {
      if (err) return;

      if (isValidAccount(values)) {
        const { email } = values;
        login({ variables: { email } }).then(() => history.push('/'));
      } else {
        Modal.error({
          title: 'Fail',
          content: 'invalid Account!',
        });
      }
    });
  };

  const toggleModal = () => {
    setModalState({
      ...modalState,
      visible: !modalState.visible,
    });
  };

  return (
    <Layout>
      <Content>
        <Row
          type="flex"
          justify="space-around"
          align="middle"
          style={{ height: '100vh' }}
        >
          <Col span={6} style={{ maxWidth: '300px' }}>
            <Form onSubmit={onLogin} className="login-form">
              <Form.Item>
                {getFieldDecorator('email', {
                  rules: [
                    { required: true, message: 'Please input your username!' },
                  ],
                })(
                  <Input
                    prefix={
                      <Icon type="user" style={{ color: 'rgba(0,0,0,.25)' }} />
                    }
                    placeholder="Username"
                  />,
                )}
              </Form.Item>
              <Form.Item>
                {getFieldDecorator('password', {
                  rules: [
                    { required: true, message: 'Please input your Password!' },
                  ],
                })(
                  <Input
                    prefix={
                      <Icon type="lock" style={{ color: 'rgba(0,0,0,.25)' }} />
                    }
                    type="password"
                    placeholder="Password"
                  />,
                )}
              </Form.Item>
              <Form.Item>
                <Button
                  type="primary"
                  htmlType="submit"
                  className="login-form-button"
                  style={{ width: '100%' }}
                >
                  Log in
                </Button>
                <Button block onClick={toggleModal}>
                  Sign Up
                </Button>
              </Form.Item>
            </Form>
          </Col>
        </Row>
      </Content>
      <Modal
        onCancel={toggleModal}
        className="modal-card hide"
        visible={modalState.visible}
      >
        <SignUp onCancel={toggleModal} isCreate="true" />
      </Modal>
    </Layout>
  );
}

export default Form.create()(Login);

// vue-with-rest/src/pages/Login.vue
<template>
  <a-layout id="login">
    <a-layout-content>
        <a-row type="flex" align="middle" class="login-container" justify="center">
          <a-col>
            <a-row class="login-container-inner">
              <a-col><h3>LOGIN</h3></a-col>
              <a-col>
                <a-form
                  :form="form"
                >
                  <a-form-item
                    :validate-status="emailError() ? 'error' : ''"
                    :help="emailError() || ''
                  ">
                    <a-input
                      v-decorator="['email',
                      {
                        rules: [{ required: true, message: '이메일을 입력하세요' }]
                      }]"
                      :autoFocus="true"
                      autocomplete="off"
                      placeholder="이메일"
                    >
                      <a-icon slot="prefix" type="user" style="color:rgba(0,0,0,.25)" />
                    </a-input>
                  </a-form-item>
                  <a-form-item
                    :validate-status="passwordError() ? 'error' : ''"
                    :help="passwordError() || ''"
                  >
                    <a-input
                      v-decorator="['password',
                      {
                        rules: [{ required: true, message: '비밀번호를 입력하세요' }]
                      }]"
                      type="password"
                      autocomplete="off"
                      placeholder="비밀번호"
                      @pressEnter="onLogin"
                    >
                      <a-icon slot="prefix" type="lock" style="color:rgba(0,0,0,.25)" />
                    </a-input>
                  </a-form-item>
                  <a-form-item>
                    <a-button
                      type="primary"
                      block
                      class="btn-login"
                      :disabled="hasErrors(form.getFieldsError())"
                      @click="onLogin"
                    >
                      Login
                    </a-button>
                    <router-link to="/user">
                      <a-button
                        block
                      >
                        Sign Up
                      </a-button>
                    </router-link>
                  </a-form-item>
                </a-form>
              </a-col>
            </a-row>
          </a-col>
        </a-row>
    </a-layout-content>
  </a-layout>
</template>

<script>
import { store } from '@/store';

function hasErrors(fieldsError) {
  return Object.keys(fieldsError).some(field => fieldsError[field]);
}

export default {
  name: 'Login',
  data() {
    return {
      hasErrors,
      form: this.$form.createForm(this),
    };
  },
  methods: {
    emailError() {
      const { getFieldError, isFieldTouched } = this.form;
      return isFieldTouched('email') && getFieldError('email');
    },
    passwordError() {
      const { getFieldError, isFieldTouched } = this.form;
      return isFieldTouched('password') && getFieldError('password');
    },
    onLogin() {
      this.form.validateFields((err, { email, password }) => {
        if (err) return;

        const isAvailable = store.getters.isAvailableAccount(email, password);
        if (isAvailable) {
          store.commit('login', { email, password });
          this.$router.push('/home');
        } else {
          this.$warning({
            title: 'Login failed',
            content: 'not exist account',
          });
        }
      });
    },
  },
};
</script>

<style lang="scss" scoped>
@import '@/styles/variables.scss';

.login-container{
  height:100vh;
  background-color:$white-color;

  &-inner{
    text-align:center;

    img{
      width:80%;
    }

    & > div:not(.text-area){
      max-width:300px;
      min-width:300px;
      margin: 0 auto;
    }

    .title{
      margin:0.5em 0;
    }

    .ant-form-item{
      margin-bottom:10px;
    }
  }
}
</style>
