// react-with-rest/src/components/example/list/Content.js
import React, { useState, useEffect } from 'react';
import { useParams } from 'react-router-dom';
import { shallowEqual, useSelector, useDispatch } from 'react-redux';
import { Card, List, Modal, Layout } from 'antd';
import { WithContentLayout } from '@/layouts';
import { post } from '@/store/actions';
import { Spinner } from '@/components/commons';

import '@/styles/app/components/example/list/Content.scss';

const { Content: ContentLayout } = Layout;

const Content = () => {
  
  const dispatch = useDispatch();
  const { category = 'posts' } = useParams();
  const { posts: items, comments } = useSelector(state => state.fetchData, shallowEqual);
  const { isLoading } = useSelector(state => state.status, shallowEqual);

  useEffect(() => {
    const action = async () => {
      if (!items) {
        dispatch(post.fetchDataAsync(category));
      }
    }
    action()
  }, [items, category, dispatch]);
  
  const [ modalState, setModalState ] = useState({
    id: '',
    title: '',
    content: '',
    visible: false,
    children: [],
  });

  const toggleModal = (item = {}) => {
    const { id = '', title = '', body = '' } = item;
    const visible = !modalState.visible;
    const children = comments[id] || [];
    setModalState({
      ...modalState,
      id,
      title,
      visible,
      children,
      content: body,
    });
  }

  const onRemoveItem = () => {
    const { id } = modalState;
    const idx = items.findIndex(obj => obj.id === id);
    items.splice(idx, 1);
    toggleModal();
  }
  
  return (
    <ContentLayout className="list-content-layout">
      { isLoading ? <Spinner size="large" /> : null}
      <List
        grid={{ gutter: 16, column: 4 }}
        dataSource={items}
        renderItem={item => (
          <List.Item>
            <Card
              title={item.title}
              onClick={() => toggleModal(item)}
            />
          </List.Item>
        )}
      />
      <Modal
        okText="Remove"
        cancelText="close"
        title={modalState.title}  
        visible={modalState.visible}
        width={`${100/3}%`}
        onOk={onRemoveItem}
        onCancel={() => toggleModal()}
      >
        <div className="modal-title">Content</div>
        <Card className="modal-card">
          {modalState.content}
        </Card>

        <div className="modal-title">Child</div>
        <Card className="modal-card modal-card-child">
          {modalState.children.map(child => (
            <Card
              key={child.id}
              bodyStyle={{ margin: '5px 0px' }}
              className="modal-card"
            >
              {JSON.stringify(child)}
            </Card>
          ))}
        </Card>
      </Modal>        
    </ContentLayout>
  )
}

export default WithContentLayout(Content);

// vue-with-rest/src/components/example/layout/list/Content.vue
<template>
  <div>
    <virtual-list :size="100" :remain="10">
      <a-list :grid="{ gutter: 16, column: 4 }" :dataSource="data">
        <a-list-item slot="renderItem" slot-scope="item">
            <a-card :title="item.title" @click="toggleModal(item.id)"/>
        </a-list-item>
      </a-list>
    </virtual-list>

    <a-modal
      okText="Remove"
      cancelText="close"
      :title="modal.title"
      :visible="modal.visible"
      :width="modalWidth"
      @ok="onRemoveItem"
      @cancel="toggleModal"
    >
      <div class="modalTitle">Content</div>
      <a-card class="modalCard">
        <template v-slot:extra>
          {{modal.content}}
        </template>
      </a-card>

      <div class="modalTitle">Child</div>
      <a-card class="modalCard">
          <template v-slot:extra>
          <virtual-list :size="100" :remain="5">
              <a-card
              v-for="item of modal.data"
              :key="item.id"
              :bodyStyle="modal.bodyStyle"
              >
              {{item}}
              </a-card>
          </virtual-list>
          </template>
      </a-card>
    </a-modal>
  </div>
</template>
<script>
import virtualList from 'vue-virtual-scroll-list';
import { store, type } from '@/store';

export default {
  name: 'Content',
  components: {
    'virtual-list': virtualList,
  },
  props: {
    category: {
      type: String,
      default: null,
    },
  },
  data() {
    return {
      data: [],
      modal: {},
      initModal: {
        id: 0,
        title: '',
        content: '',
        visible: false,
        data: [],
        bodyStyle: {
          margin: '5px 0px',
        },
      },
    };
  },
  mounted() {
    this.initModalData();
    this.data = store.state.fetchData.posts;
  },
  computed: {
    modalWidth() {
      return `${100 / 3}%`;
    },
  },
  methods: {
    async toggleModal(id) {
      this.modal.visible = !this.modal.visible;

      // when open modal
      if (this.modal.visible) {
        this.setModalData(id);
      } else {
        this.initModalData();
      }
    },
    initModalData() {
      this.modal = { ...this.initModal };
    },
    setModalData(id) {
      const selectedItem = this.data.find(el => el.id === id);
      if (!selectedItem) {
        return;
      }

      this.modal.id = selectedItem.id;
      this.modal.title = selectedItem.title;
      this.modal.content = selectedItem;
      this.getChildData(selectedItem.id);
    },
    getChildData(postId) {
      this.modal.data = store.getters.comments(postId);
    },
    onRemoveItem() {
      const { id } = this.modal;
      store.commit(type.DELETE_ITEM, id);
      this.toggleModal();
    },
  },
};
</script>
<style lang="scss" scoped>
.modalCard .ant-card.ant-card-bordered{
  margin: 7px 0px;
}

.ant-card-bordered:not(.modalCard){
    cursor: pointer;

    &:hover{
      box-shadow: 1px 1px 3px black;
    }

    &:active{
      box-shadow: 0px 0px 0px;
    }
}

.ant-modal-footer{
  display: none !important;
}

.modalTitle{
  padding-top: 10px;
  font-size: 20px;
}

.modalCard{
  padding: 5px;
}

</style>>
