// vue-with-rest/src/components/example/layout/list/Header.vue
<template>
    <div>
        <a-button type="primary" @click="toggleModal">Add</a-button>

        <a-modal
            :visible="modal.visible"
            title="Add Item"
            okText="Create"
            cancelText="Cancel"
            @cancel="toggleModal"
            @ok="onCreateItem"
        >
            <a-form :form="form">
                <a-form-item label="title" :label-col="{ span: 5 }" :wrapper-col="{ span: 15 }">
                <a-input
                    v-decorator="['title', { rules: [{ required: true, message: 'Please input title!' }] }]"
                />
                </a-form-item>
                <a-form-item label="body" :label-col="{ span: 5 }" :wrapper-col="{ span: 15 }">
                <a-input
                    v-decorator="['body', { rules: [{ required: true, message: 'Please input body!' }] }]"
                />
                </a-form-item>
            </a-form>
        </a-modal>
    </div>
</template>

<script>
import { store, type } from '@/store';

export default {
  name: 'ContentHeader',
  data() {
    return {
      form: this.$form.createForm(this, { name: 'createForm' }),
      modal: {
        visible: false,
      },
    };
  },
  methods: {
    toggleModal() {
      this.modal.visible = !this.modal.visible;
    },
    onCreateItem() {
      this.form.validateFields((err, values) => {
        if (err) return;

        store.commit(type.ADD_ITEM, values);
        this.toggleModal();
      });
    },
  },

};
</script>

<style lang="scss" scoped>
.ant-btn.ant-btn-primary{
    float: right;
}
</style>

// react-with-graphql/src/components/example/list/Header.js
import React, { useState } from 'react';
import { useApolloClient } from '@apollo/react-hooks';
import { Form, Button, Input, Modal } from 'antd';

import { ALL_POSTS } from '@/graphql/queries/posts';
import '@/styles/app/components/example/list/Header.scss';

const Header = ({ form, localPosts, beginRefeshPosts }) => {

  const apolloClient = useApolloClient();
  const { getFieldDecorator } = form;
  const [ modalState, setModalState ] = useState({
    visible: false,
  });

  const toggleModal = () => {
    setModalState({
      ...modalState,
      visible: !modalState.visible,
    });
  }

  const onCreateItem = () => {
    form.validateFields((err, values) => {
      if(err) return;

      const maxIdPost = localPosts.sort((a, b) => b.id - a.id)[0];
      const maxId = ( maxIdPost ) ? maxIdPost.id/1 + 1 : 0;
      values.id = maxId;
      localPosts.unshift(values);
      apolloClient.writeQuery({
        query: ALL_POSTS,
        data: { allPosts: localPosts }
      });
      beginRefeshPosts(true);
      toggleModal();
    })
  }

  return (
    <div className="content_header">
      <Button type="primary" onClick={toggleModal}>
        Add
      </Button>

      <Modal
        visible={modalState.visible}
        title="Add Item"
        okText="Create"
        cancelText="Cancel"
        onOk={onCreateItem}
        onCancel={toggleModal}
      >
        <Form>
          <Form.Item label="title">
            {getFieldDecorator('title', {
              rules: [{ required: true, message: 'Please input title!' }]
            })(
              <Input />
              )}
          </Form.Item>
          <Form.Item label="body">
            {getFieldDecorator('body', {
              rules: [{ required: true, message: 'Please input body!' }]
            })(
              <Input />
            )}
          </Form.Item>
        </Form>
      </Modal>
    </div>
  )
}

export default Form.create({ name: 'list_header_form' })(Header);
