// vue-with-rest/src/layouts/Header.vue
<template>
  <a-layout-header>
    <a-row type="flex" justify="space-between" align="middle" class="header">
      <a-col span="24">
        <h3 :style="{ color: '#fff'}">Header</h3>
      </a-col>
    </a-row>
  </a-layout-header>
</template>

<script>
export default {
  name: 'Header',
  data() {
    return {

    };
  },
};
</script>

<style lang="scss" scoped>
.header{
  text-align: center;
}
</style>

// react-default/src/layouts/Header.js
import React from 'react';
import { Layout, Row, Col } from 'antd';

const { Header } = Layout;

function HeaderComponent() {
  return (
    <Header>
      <Row
        type="flex"
        justify="space-between"
        align="middle"
        className="header"
      >
        <Col span={24}>
          <h3>Header</h3>
        </Col>
      </Row>
    </Header>
  );
}

export default HeaderComponent;
